// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectWirelessAdb(arg1, arg2) {
  return window['go']['backend']['App']['ConnectWirelessAdb'](arg1, arg2);
}

export function DisconnectWirelessAdb(arg1, arg2) {
  return window['go']['backend']['App']['DisconnectWirelessAdb'](arg1, arg2);
}

export function EnableWirelessAdb(arg1) {
  return window['go']['backend']['App']['EnableWirelessAdb'](arg1);
}

export function FlashPartition(arg1, arg2) {
  return window['go']['backend']['App']['FlashPartition'](arg1, arg2);
}

export function GetDeviceInfo() {
  return window['go']['backend']['App']['GetDeviceInfo']();
}

export function GetDeviceMode() {
  return window['go']['backend']['App']['GetDeviceMode']();
}

export function GetDevices() {
  return window['go']['backend']['App']['GetDevices']();
}

export function GetFastbootDevices() {
  return window['go']['backend']['App']['GetFastbootDevices']();
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function InstallPackage(arg1) {
  return window['go']['backend']['App']['InstallPackage'](arg1);
}

export function ListFiles(arg1) {
  return window['go']['backend']['App']['ListFiles'](arg1);
}

export function PullFile(arg1, arg2) {
  return window['go']['backend']['App']['PullFile'](arg1, arg2);
}

export function PushFile(arg1, arg2) {
  return window['go']['backend']['App']['PushFile'](arg1, arg2);
}

export function Reboot(arg1) {
  return window['go']['backend']['App']['Reboot'](arg1);
}

export function SelectApkFile() {
  return window['go']['backend']['App']['SelectApkFile']();
}

export function SelectDirectoryForPull() {
  return window['go']['backend']['App']['SelectDirectoryForPull']();
}

export function SelectDirectoryToPush() {
  return window['go']['backend']['App']['SelectDirectoryToPush']();
}

export function SelectFileToPush() {
  return window['go']['backend']['App']['SelectFileToPush']();
}

export function SelectImageFile() {
  return window['go']['backend']['App']['SelectImageFile']();
}

export function SelectSaveDirectory(arg1) {
  return window['go']['backend']['App']['SelectSaveDirectory'](arg1);
}

export function SelectZipFile() {
  return window['go']['backend']['App']['SelectZipFile']();
}

export function SideloadPackage(arg1) {
  return window['go']['backend']['App']['SideloadPackage'](arg1);
}

export function UninstallPackage(arg1) {
  return window['go']['backend']['App']['UninstallPackage'](arg1);
}

export function WipeData() {
  return window['go']['backend']['App']['WipeData']();
}
